# Generated by Django 4.2.20 on 2025-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_content_document_file_document_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created',
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
