# Generated by Django 4.2.20 on 2025-04-17 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_create_documenthistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenthistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BpmnDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('xml', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_diagrams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BPMN диаграмма',
                'verbose_name_plural': 'BPMN диаграммы',
                'ordering': ['-updated_at'],
            },
        ),
    ]
