# Generated by Django 5.0.1 on 2025-09-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_documenthistory_id_bpmndiagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmndiagram',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_diagrams', to='myapp.process'),
        ),
    ]
