# Generated by Django 5.0.1 on 2025-09-15 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bpmndiagram_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Чтение'), ('write', 'Редактирование'), ('admin', 'Администратор')], default='read', max_length=10)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='myapp.document')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к документу',
                'verbose_name_plural': 'Доступы к документам',
                'unique_together': {('document', 'user')},
            },
        ),
    ]
