# Generated by Django 5.0.1 on 2025-09-18 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_documentaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование'), ('admin', 'Администратор')], default='view', max_length=10)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='myapp.bpmndiagram')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_bpmn_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к BPMN диаграмме',
                'verbose_name_plural': 'Доступы к BPMN диаграммам',
                'unique_together': {('diagram', 'user')},
            },
        ),
    ]
