# Generated by Django 4.2.20 on 2025-10-16 01:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_update_userprofile_avatar_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Руководитель'), ('secretary', 'Секретарь'), ('employee', 'Сотрудник'), ('viewer', 'Наблюдатель')], max_length=50, unique=True, verbose_name='Название роли')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет роли (HEX)')),
                ('icon', models.CharField(default='fas fa-user', max_length=50, verbose_name='Иконка роли')),
                ('can_create_documents', models.BooleanField(default=False, verbose_name='Может создавать документы')),
                ('can_edit_documents', models.BooleanField(default=False, verbose_name='Может редактировать документы')),
                ('can_delete_documents', models.BooleanField(default=False, verbose_name='Может удалять документы')),
                ('can_share_documents', models.BooleanField(default=False, verbose_name='Может делиться документами')),
                ('can_create_processes', models.BooleanField(default=False, verbose_name='Может создавать процессы')),
                ('can_edit_processes', models.BooleanField(default=False, verbose_name='Может редактировать процессы')),
                ('can_delete_processes', models.BooleanField(default=False, verbose_name='Может удалять процессы')),
                ('can_manage_processes', models.BooleanField(default=False, verbose_name='Может управлять процессами')),
                ('can_create_tasks', models.BooleanField(default=False, verbose_name='Может создавать задачи')),
                ('can_edit_tasks', models.BooleanField(default=False, verbose_name='Может редактировать задачи')),
                ('can_delete_tasks', models.BooleanField(default=False, verbose_name='Может удалять задачи')),
                ('can_assign_tasks', models.BooleanField(default=False, verbose_name='Может назначать задачи')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Может управлять пользователями')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='Может просматривать аналитику')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Может управлять ролями')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания профиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP последнего входа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.role', verbose_name='Роль'),
        ),
    ]
