# Generated by Django 5.0.1 on 2025-10-18 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_add_role_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='digital_stamp',
            field=models.TextField(blank=True, null=True, verbose_name='Электронная печать (base64)'),
        ),
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись (base64)'),
        ),
        migrations.AddField(
            model_name='document',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи'),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подписант'),
        ),
        migrations.AddField(
            model_name='document',
            name='stamp_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные печати'),
        ),
        migrations.AddField(
            model_name='document',
            name='stamp_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проставления печати'),
        ),
        migrations.AddField(
            model_name='document',
            name='stamped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamped_documents', to=settings.AUTH_USER_MODEL, verbose_name='Кто проставил печать'),
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
